-- And Then — layered page privacy: visibility × contribution access, a
-- shared access code, a lifecycle lock, and contributor blocking.
--
-- Replaces access_mode ('invite_only'/'public'), which nothing has ever
-- actually read — canContribute in Memorial.jsx only checked is_paid +
-- ownership, so every existing page is already fully public to view and
-- open to anyone with the link to contribute. This migration backfills
-- every memorial to visibility='public', contribution_access='open',
-- which is exactly that real-world behavior, so nothing changes for an
-- existing page until its steward touches these new Settings.
--
-- Two independent axes, not tiers a steward has to pick one of:
--   visibility:         public | unlisted | private
--   contribution_access: open | code_required
-- A private page always gates contribution behind the same code it gates
-- viewing behind — no second code, per the product decision to keep this
-- simple. access_code is generated by the app (uid()-style short code),
-- not this migration, the first time a steward turns on Private or
-- Code-required.
--
-- memorials has never had a SELECT column grant before (anon could read
-- every column of every row). Adding one now — both because access_code
-- must never be anon/authenticated-readable directly (only the new
-- get_memorial_page() RPC, which is SECURITY DEFINER and bypasses grants,
-- may compare it), and to close a pre-existing minor leak of
-- stripe_customer_id/stripe_subscription_id while touching this anyway.
--
-- Idempotent. Run in Supabase → SQL Editor.

-- 1) memorials: new columns, drop access_mode --------------------------------

alter table public.memorials add column if not exists visibility text;
update public.memorials set visibility = 'public' where visibility is null;
alter table public.memorials alter column visibility set default 'public';
alter table public.memorials alter column visibility set not null;
alter table public.memorials drop constraint if exists memorials_visibility_check;
alter table public.memorials
  add constraint memorials_visibility_check check (visibility in ('public', 'unlisted', 'private'));

alter table public.memorials add column if not exists contribution_access text;
update public.memorials set contribution_access = 'open' where contribution_access is null;
alter table public.memorials alter column contribution_access set default 'open';
alter table public.memorials alter column contribution_access set not null;
alter table public.memorials drop constraint if exists memorials_contribution_access_check;
alter table public.memorials
  add constraint memorials_contribution_access_check check (contribution_access in ('open', 'code_required'));

alter table public.memorials add column if not exists access_code text;

alter table public.memorials add column if not exists closed_to_submissions boolean not null default false;

-- access_mode's only writer/UI was removed in a previous change; confirmed
-- unread anywhere in the app before dropping.
alter table public.memorials drop column if exists access_mode;

grant update (visibility, contribution_access, access_code, closed_to_submissions)
  on public.memorials to authenticated;

-- 2) memorials: first-ever column-scoped SELECT grant -------------------------

revoke select on public.memorials from anon, authenticated;

grant select (
  id, name, born, passed, description, photo_url, steward_id, invite_code,
  created_at, require_approval, prompt, is_paid, anniversary_notified_on,
  invite_message, prompts, slug, steward_relation, paused, crop_x, crop_y,
  visibility, contribution_access, closed_to_submissions
) on public.memorials to anon;

-- Stewards additionally need to read access_code back for the Settings
-- screen (row visibility is still gated by the SELECT policy below, so
-- this only ever applies to a memorial a steward is actually authorized on).
grant select (
  id, name, born, passed, description, photo_url, steward_id, invite_code,
  created_at, require_approval, prompt, is_paid, anniversary_notified_on,
  invite_message, prompts, slug, steward_relation, paused, crop_x, crop_y,
  visibility, contribution_access, closed_to_submissions, access_code
) on public.memorials to authenticated;

-- 3) memorials: first-ever row-level SELECT policy -----------------------------

-- Public/unlisted rows stay readable by anyone (unlisted only differs by
-- not being indexed — see Memorial.jsx's robots-meta handling, a frontend
-- concern, not an RLS one). Private rows are no longer selectable via the
-- plain REST API at all, by anyone but a steward — get_memorial_page()
-- below is the sanctioned, code-checked way in for everyone else.
drop policy if exists "memorials visible per visibility" on public.memorials;
create policy "memorials visible per visibility"
  on public.memorials for select
  to anon, authenticated
  using (visibility in ('public', 'unlisted') or public.is_memorial_steward(id));

-- 4) get_memorial_page(): the single load path for the public page ------------

-- Plain RLS can't gate "did this stateless request already prove a code" —
-- each REST call is its own transaction. A SECURITY DEFINER function is the
-- standard safe way to check a client-supplied secret against a column the
-- client can't otherwise read. Returns null/[] identically whether the page
-- doesn't exist or is private with a wrong/missing code, so a guess can't
-- be used to fingerprint whether a given identifier is a real page.
create or replace function public.get_memorial_page(p_identifier text, p_code text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  m public.memorials%rowtype;
  is_steward boolean;
  code_ok boolean;
begin
  select * into m from public.memorials
  where invite_code = p_identifier or slug = p_identifier
  limit 1;

  if not found then
    return jsonb_build_object('memorial', null, 'contributions', '[]'::jsonb, 'code_verified', false);
  end if;

  is_steward := public.is_memorial_steward(m.id);
  code_ok := m.access_code is not null and p_code is not null and p_code = m.access_code;

  if m.visibility = 'private' and not is_steward and not code_ok then
    return jsonb_build_object('memorial', null, 'contributions', '[]'::jsonb, 'code_verified', false);
  end if;

  return jsonb_build_object(
    'memorial', to_jsonb(m) - 'access_code' - 'stripe_customer_id' - 'stripe_subscription_id',
    'contributions', coalesce((
      select jsonb_agg(to_jsonb(c) - 'contributor_email' - 'submitted_code' order by c.created_at desc)
      from public.contributions c
      where c.memorial_id = m.id and c.status = 'approved'
    ), '[]'::jsonb),
    -- A steward always counts as "code verified" too — they shouldn't need
    -- their own page's secret to be treated as someone who's cleared the
    -- gate (this is what the frontend's canContribute check reuses for the
    -- code-required-contribution case, so a steward viewing their own page
    -- is never asked to type a code back at themselves).
    'code_verified', code_ok or is_steward
  );
end;
$$;

grant execute on function public.get_memorial_page(text, text) to anon, authenticated;

-- 5) blocked_contributors -------------------------------------------------------

-- Contributors have no accounts, sessions, or verified identity — the only
-- signal a steward has to go on is whatever the flagged submission itself
-- captured: contributor_email when given (optional today), else the exact
-- contributor_name. Not spoof-proof, but it's everything the current
-- submission flow captures, per product decision to key off what already
-- exists rather than add new identity infrastructure.
create table if not exists public.blocked_contributors (
  id uuid primary key default gen_random_uuid(),
  memorial_id uuid not null references public.memorials(id) on delete cascade,
  identifier text not null,
  identifier_type text not null check (identifier_type in ('email', 'name')),
  blocked_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique (memorial_id, identifier_type, identifier)
);

alter table public.blocked_contributors enable row level security;
revoke all on public.blocked_contributors from anon, authenticated, public;

drop policy if exists "stewards manage their blocked contributors" on public.blocked_contributors;
create policy "stewards manage their blocked contributors"
  on public.blocked_contributors for all
  to authenticated
  using (public.is_memorial_steward(memorial_id))
  with check (public.is_memorial_steward(memorial_id));
grant select, insert, delete on public.blocked_contributors to authenticated;

create or replace function public.is_contributor_blocked(p_memorial_id uuid, p_name text, p_email text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.blocked_contributors b
    where b.memorial_id = p_memorial_id
      and (
        (p_email is not null and b.identifier_type = 'email' and b.identifier = lower(trim(p_email)))
        or (b.identifier_type = 'name' and b.identifier = lower(trim(coalesce(p_name, ''))))
      )
  );
$$;

-- 6) contributions: submitted_code column, rewritten INSERT policy ------------

-- Carries a visitor's typed access code exactly once, for the check below
-- to compare — never selectable back (same "sensitive column, no SELECT
-- grant" idiom as contributor_email), so the code doesn't sit in a
-- readable column after the fact.
alter table public.contributions add column if not exists submitted_code text;

-- memorials now has a real SELECT policy (private rows hidden from anon),
-- so a plain `exists (select ... from memorials ...)` inline in this INSERT
-- policy would itself get silently filtered by that same policy — an anon
-- submitter with a correct code could never see the private row to satisfy
-- the check. Same escape hatch as is_memorial_steward()/
-- free_tier_contribution_count(): a SECURITY DEFINER function looks the
-- memorial up once, unfiltered, and evaluates every rule against it.
create or replace function public.can_insert_contribution(p_memorial_id uuid, p_code text, p_status text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  m public.memorials%rowtype;
  is_steward boolean;
begin
  select * into m from public.memorials where id = p_memorial_id;
  if not found or m.closed_to_submissions then
    return false;
  end if;

  is_steward := public.is_memorial_steward(m.id);

  if not (m.is_paid or (is_steward and public.free_tier_contribution_count(m.id) < 5)) then
    return false;
  end if;

  -- A steward never needs their own page's code to add a memory to it.
  if not (
    is_steward
    or (m.visibility <> 'private' and m.contribution_access = 'open')
    or (m.access_code is not null and p_code = m.access_code)
  ) then
    return false;
  end if;

  return p_status = case when m.require_approval then 'pending' else 'approved' end;
end;
$$;

drop policy if exists "anyone can contribute to a real memorial" on public.contributions;
create policy "anyone can contribute to a real memorial"
  on public.contributions for insert
  to anon, authenticated
  with check (
    length(trim(coalesce(contributor_name, ''))) > 0
    and not public.is_contributor_blocked(memorial_id, contributor_name, contributor_email)
    and public.can_insert_contribution(memorial_id, submitted_code, status)
  );

-- 7) contributions: visibility-aware read policy -------------------------------

-- Before this, "approved memories are public" had no visibility awareness —
-- anyone who knew/guessed a private memorial's id could still read its
-- approved contributions straight from the table, even though the memorial
-- row itself is now hidden. Unlike the INSERT check above, this one should
-- NOT bypass memorials' RLS — a plain (unwrapped) subquery is exactly what's
-- wanted here, since it only finds the memorial row (and so only allows the
-- read) when memorials' own "visible per visibility" policy already permits
-- it for this same caller (public/unlisted, or a steward on their own page).
drop policy if exists "approved memories are public" on public.contributions;
create policy "approved memories are public"
  on public.contributions for select
  to anon, authenticated
  using (
    status = 'approved'
    and exists (select 1 from public.memorials m where m.id = memorial_id)
  );
